### PR TITLE
Use daemon thread instead of user thread

### PR DESCRIPTION
**Pull request by Misterhex**
Usage of user thread prevent application's main thread from exiting.

### CODE REVIEW

**Comment by scottfrederick** [comment]
@Misterhex This project is not being actively maintained. We don't plan on creating any new releases going forward. 

See the noticed at the top of the README: 

```
Use of this library is strongly discouraged. Providing a library that essentially disables or 
bypasses a major facet of inter-application communication security, while convenient for 
development, also makes it easy for developers to deploy insecure applications to 
production. Platforms like Cloud Foundry have made it easier to centralize SSL certificate 
management at an operations level, eliminating any need for a library like this.
```

What's your use case for this library?

**Comment by Misterhex** [comment]
@scottfrederick 

Hi, we are using this in our testing environment to trust self signed certificates.

When adding this to classpath, we noticed SslCertificateTruster is spawning a user thread in the executor threadpool. 

This thread caused our main thread not to exit and block indefinitely.

**Comment by scottfrederick** [comment]
@Misterhex I'm sorry that you're having problems with the library, but I suggest you use one of the alternative instead of patching the lib. 

One good alternative is to add the self-signed cert to the list of [BOSH trusted certs](http://bosh.io/docs/trusted-certs.html). If you are using Pivotal Cloud Foundry, you can extract the Ops Manager root CA cert and [add that to the trusted certificates](https://docs.pivotal.io/pivotalcf/2-1/customizing/trusted-certificates.html).

**Comment by Misterhex** [comment]
@scottfrederick no problem scott, thanks for getting back.

**Pull request closed without merging**
